#Consul and Gateway Properties
spring:
  cloud:
    consul:
      discovery:
        hostname: localhost
        register: false
    gateway:
      routes:
      - id: Employee-Service
        uri: lb://Employee-Service
        predicates:
        - Path=/employee/**
      - id: Training-Service
        uri: lb://Training-Service
        predicates:
        - Path=/training/**